name: Build and Publish Avalonia App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    concurrency:
      group: build-and-publish
      cancel-in-progress: true

    env:
      Solution_Name: AvaloniaApplication.sln

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            ~/.local/share/NuGet/Cache
          key: |
            ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Install Avalonia Templates
        run: dotnet new install Avalonia.Templates

      - name: Restore dependencies
        run: dotnet restore ${{ env.Solution_Name }}

      - name: Build solution
        run: dotnet build ${{ env.Solution_Name }} --configuration Release

      - name: Start MySQL container
        run: |
          docker run -d --platform linux/amd64 --name mysql-container -p 3306:3306 ${{ secrets.DOCKER_USERNAME }}/sample-mysql:latest

      - name: Wait for MySQL to be ready
        run: |
          for i in {30..0}; do
            if docker exec mysql-container mysql -u sample_user -psample_password -e 'SELECT 1' sample_db &> /dev/null; then
              echo "MySQL is up and running"
              break
            fi
            echo 'Waiting for MySQL to be ready...'
            sleep 2
          done
          if [ "$i" = 0 ]; then
            echo "MySQL did not become ready in time."
            exit 1
          fi
      
      - name: Run tests
        run: |
          dotnet test ${{ env.Solution_Name }} --configuration Release

      - name: Stop and remove MySQL container
        if: always()
        run: |
          docker stop mysql-container
          docker rm mysql-container
      
      - name: Publish Avalonia app
        run: dotnet publish ${{ env.Solution_Name }} --configuration Release -o ${{ github.workspace }}/publish

      - name: Cache publish output
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/publish
          key: ｜
            ${{ runner.os }}-publish-${{ hashFiles('**/*.csproj') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-publish-${{ hashFiles('**/*.csproj') }}-
            
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Published Avalonia App
          path: ${{ github.workspace }}/publish
          
      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latestTag=$(git tag --sort=-creatordate | head -n 1)
          echo "Latest tag is: $latestTag"
          echo "::set-output name=latestTag::$latestTag"
        shell: bash
        
      - name: Determine next version
        id: next_version
        run: |
          latestTag=${{ steps.get_latest_tag.outputs.latestTag }}
          echo "Latest tag: $latestTag"
          if [[ $latestTag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
            nextVersion="v$major.$minor.$((patch + 1))"
          else
            nextVersion="v1.0.0"
          fi
          echo "Next version: $nextVersion"
          echo "::set-output name=VERSION::$nextVersion"
        shell: bash

      - name: Create GitHub Release
        if: ${{ startsWith(github.event.head_commit.message, 'Merge pull request') }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.next_version.outputs.VERSION }}
          release_name: Release ${{ steps.next_version.outputs.VERSION }}
          body: |
            Release of the .NET project
          draft: false
          prerelease: false
          
      - name: Compress Artifacts
        if: ${{ startsWith(github.event.head_commit.message, 'Merge pull request') }}
        run: |
          choco install zip -y
          cd "${{ github.workspace }}\\publish"
          zip -r ..\\Published_Avalonia_App.zip *
        shell: bash

      - name: Upload Release Asset
        if: ${{ startsWith(github.event.head_commit.message, 'Merge pull request') }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}\\Published_Avalonia_App.zip
          asset_name: Published_Avalonia_App.zip
          asset_content_type: application/zip
